name: Deploy

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: "self-hosted"

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Deploy to Dokku
      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@10.10.228.209:22/docs"
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}